"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const morgan_1 = __importDefault(require("morgan"));
const helmet_1 = __importDefault(require("helmet"));
const { NODE_ENV } = process.env;
const dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
const middlewares_1 = __importDefault(require("./middlewares"));
const task_scheduler_1 = require("./task-scheduler");
const app = (0, express_1.default)();
const morganOption = NODE_ENV === "production" ? "tiny" : "common";
app.use((0, morgan_1.default)(morganOption));
app.use((0, helmet_1.default)());
app.use(express_1.default.json());
(0, task_scheduler_1.taskScheduler)();
app.use(middlewares_1.default.notFound);
app.use(middlewares_1.default.errorHandler);
exports.default = app;
